[phases.setup]
nixPkgs = [
  "php83",
  "php83Packages.composer",
  "php83Extensions.pdo_mysql",
  "php83Extensions.mbstring",
  "php83Extensions.zip",
  "php83Extensions.curl",
  "php83Extensions.intl",
  "php83Extensions.fileinfo",
  "php83Extensions.gd",
  "php83Extensions.exif",
  "php83Extensions.bcmath",
  "php83Extensions.opcache",
  "php83Extensions.dom"
]

[phases.install]
cmds = ["composer install --no-dev --optimize-autoloader"]

[phases.build]
cmds = [
  "php artisan config:cache",
  "php artisan route:cache",
  "php artisan view:cache"
]

[start]
cmd = "php -S 0.0.0.0:8080 -t public public/index.php"
